Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

# AllCops:
# Excludes:
#   - db/schema.rb



# Style/FrozenStringLiteralComment:
#   Enabled: false

# Style/HashEachMethods:
#   Enabled: true

# Style/HashTransformKeys:
#   Enabled: true

# Style/HashTransformValues:
#   Enabled: true